# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95a8b4de8057c3f5892921b2185ffa321ba2d37f18fe7e3956e81b5e4ec7180b4f9391cdec1b3b892123d514ca80067c85bedecb0f265dcc13c358822c19b0e9

test:
  secret_key_base: deb6abf6a01c6445ea287b31884aedc645dee2d70827def91f9879e2d20cda7ed6da445b397c97f13c0c591e94e32b7afc946aa9ecde8209d300ede7698f66d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
